name: Beta Release
on:
  push:
    branches:
      - beta
  pull_request:
    branches:
      - beta
  merge_group:
    types:
      - checks_requested

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint files
        run: yarn lint

      - name: Typecheck files
        run: yarn typecheck

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run unit tests
        run: yarn test --maxWorkers=2 --coverage

  build-library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build package
        run: yarn prepack

  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build example for Web
        run: |
          yarn example expo export --platform web

  publish-beta:
    needs: [lint, test, build-library, build-web]
    runs-on: ubuntu-latest
    permissions:
      contents: write # To publish a GitHub release
      issues: write # To comment on released issues
      pull-requests: write # To comment on released pull requests
      id-token: write # To enable use of OIDC for npm provenance
    if: github.ref == 'refs/heads/beta'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures all tags are fetched

      - name: Setup
        uses: ./.github/actions/setup

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"  # Use the latest LTS version of Node.js
          registry-url: 'https://registry.npmjs.org/'  # Specify npm registry

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures  # Check the signatures to verify integrity

      - name: Release Beta
        run: npx semantic-release # Run semantic-release to manage versioning and publishing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication

          # Why NODE_AUTH_TOKEN instead of NPM_TOKEN: https://github.com/semantic-release/semantic-release/issues/2313
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # npm token for publishing package
      